language: ruby
rvm:
- 2.2

before_script:
 - chmod +x ./script/cibuild
 - bundle exec danger

install: bundle install --jobs=3 --retry=3 --without development

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
