# Site settings
title: pixyzehn
email: pixyzehn@icloud.com
author: pixyzehn
description: "Just another jekyll blog"
baseurl: ""
keywords: "Swift, pixyzehn, iOS, Objective-C, cocoa, Apple, Xcode, app store, programming"
url: "https://pixyzehn.com"
timezone: "Asia/Tokyo"
twitter_username: pixyzehn
github_username: pixyzehn

links:
  repo: 'https://github.com/pixyzehn/pixyzehn.github.io'
  github: 'https://github.com/pixyzehn'
  twitter: 'https://twitter.com/pixyzehn'
  facebook: 'https://www.facebook.com/pixyzehn'
  linkedin: 'https://www.linkedin.com/in/pixyzehn'
  stackoverflow: 'http://stackoverflow.com/users/2461812/pixyzehn'
  medium: 'https://medium.com/@pixyzehn'
  rss: 'https://pixyzehn.com/feed.xml'

pagination:
  enabled: true

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-gist

exclude: [vendor]
