# Site settings
title: pixyzehn
email: pixyzehn@icloud.com
author: pixyzehn
description: "Just another jekyll blog"
baseurl: ""
keywords: "Swift, pixyzehn, iOS, Objective-C, cocoa, Apple, Xcode, app store, programming"
url: "https://pixyzehn.com"
timezone: "Asia/Tokyo"
twitter_username: pixyzehn
github_username: pixyzehn

links:
  repo: 'https://github.com/pixyzehn/pixyzehn.github.io'
  twitter: 'https://twitter.com/pixyzehn'
  github: 'https://github.com/pixyzehn'
  linkedin: 'https://www.linkedin.com/in/pixyzehn'

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 8
paginate_path: "/page/:num"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-gist
  - jekyll-archives

exclude: [vendor]
